# Generated by Django 4.2.8 on 2024-08-22 19:01

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_alter_course_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="attachment",
            field=models.FileField(
                upload_to=courses.models.upload_to_course_attachments,
                validators=[courses.models.validate_pdf_file],
            ),
        ),
    ]
