# Generated by Django 4.2.8 on 2024-10-10 20:21

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="article",
            name="miniature",
            field=models.ImageField(
                blank=True, null=True, upload_to=articles.models.upload_to_article_miniatures
            ),
        ),
    ]
